services:
  edupgvector:
    image: pgvector/pgvector:0.8.5-pg15
    container_name: edupgvector
    restart: unless-stopped
    environment:
      POSTGRES_DB: passed_db
      POSTGRES_USER: passed
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - edupgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d edudb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  edupgvector_data: