package com.cenergy.passed_backend.global.error;

public enum ErrorCode {
    SKILL_GAP_INVALID_RESPONSE,
    SKILL_GAP_NOT_FOUND,
    ROADMAP_AI_TIMEOUT,
    ROADMAP_AI_UNAVAILABLE,
    ROADMAP_AI_INVALID_RESPONSE,
    ROADMAP_INVALID_REQUEST,
    ROADMAP_NOT_FOUND,
    MILESTONE_NOT_FOUND,
    ROADMAP_NO_COMPETENCY_TO_LEARN,
    ROADMAP_GENERATION_FAILED,
    RECOMMENDATION_INVALID_REQUEST,
    RECOMMENDATION_USER_NOT_FOUND,
    RECOMMENDATION_ALREADY_PROCESSING,
    RECOMMENDATION_POLICY_NOT_FOUND,
    RECOMMENDATION_POLICY_CONFIGURATION_INVALID,
    RECOMMENDATION_USER_SKILLS_NOT_FOUND,
    RECOMMENDATION_SKILL_DATA_INVALID
}
