package com.cenergy.passed_backend.global.error;

public enum ErrorCode {
    SKILL_GAP_INVALID_RESPONSE,
    SKILL_GAP_NOT_FOUND,
    ROADMAP_AI_TIMEOUT,
    ROADMAP_AI_UNAVAILABLE,
    ROADMAP_AI_INVALID_RESPONSE,
    ROADMAP_INVALID_REQUEST,
    ROADMAP_NOT_FOUND,
    ROADMAP_NO_COMPETENCY_TO_LEARN,
    ROADMAP_GENERATION_FAILED
}
