-- Passed PostgreSQL initial schema
-- PostgreSQL 15+ / pgvector
--
-- 설계 원칙:
-- 1. 애플리케이션 상태값은 PostgreSQL ENUM 대신 CHECK 제약으로 관리하여 변경을 쉽게 한다.
-- 2. 사용자 입력 데이터 삭제 시 하위 데이터는 CASCADE, 마스터 데이터 삭제는 RESTRICT한다.
-- 3. source_type + source_id 형태의 다형 참조는 DB 외래키로 표현할 수 없으므로
--    source_type 값만 CHECK하고 source_id 실재 여부는 서비스 계층에서 검증한다.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- =========================================================
-- 1. 사용자 · 자기소개서
-- =========================================================

CREATE TABLE users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(100) NOT NULL,
    email           varchar(255) NOT NULL,
    password        varchar(255) NOT NULL,
    field           varchar(100),
    desired_jobs    jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT chk_users_desired_jobs_array
        CHECK (desired_jobs IS NULL OR jsonb_typeof(desired_jobs) = 'array')
);

COMMENT ON COLUMN users.password IS 'bcrypt, Argon2id 등 단방향 해시만 저장';
COMMENT ON COLUMN users.desired_jobs IS '희망 직무 키워드 JSON 배열';

CREATE TABLE cover_letter_questions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_type   varchar(30) NOT NULL,
    question_text   varchar(500) NOT NULL,
    guide_text      text,
    match_weight    numeric(3,2),
    display_order   integer,
    is_active       boolean NOT NULL DEFAULT true,

    CONSTRAINT uq_cover_letter_questions_type UNIQUE (question_type),
    CONSTRAINT chk_cover_letter_questions_type
        CHECK (question_type IN ('MOTIVATION', 'PERSONALITY', 'EXPERIENCE')),
    CONSTRAINT chk_cover_letter_questions_weight
        CHECK (match_weight IS NULL OR match_weight BETWEEN 0 AND 1),
    CONSTRAINT chk_cover_letter_questions_order
        CHECK (display_order IS NULL OR display_order >= 0)
);

CREATE TABLE cover_letters (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_cover_letters_user UNIQUE (user_id),
    CONSTRAINT fk_cover_letters_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE cover_letter_items (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cover_letter_id   bigint NOT NULL,
    question_id       bigint NOT NULL,
    answer            text,
    relevance_score   numeric(4,3),
    embedding         vector(1536),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_cover_letter_items_question
        UNIQUE (cover_letter_id, question_id),
    CONSTRAINT fk_cover_letter_items_cover_letter
        FOREIGN KEY (cover_letter_id) REFERENCES cover_letters(id) ON DELETE CASCADE,
    CONSTRAINT fk_cover_letter_items_question
        FOREIGN KEY (question_id) REFERENCES cover_letter_questions(id) ON DELETE RESTRICT,
    CONSTRAINT chk_cover_letter_items_relevance
        CHECK (relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1)
);

CREATE INDEX ix_cover_letter_items_cover_letter
    ON cover_letter_items (cover_letter_id);

-- =========================================================
-- 2. 이력서 및 상세 이력
-- =========================================================

CREATE TABLE resumes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_resumes_user UNIQUE (user_id),
    CONSTRAINT fk_resumes_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE personal_infos (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id       bigint NOT NULL,
    birth_date      date,
    gender          varchar(10),
    email           varchar(255),
    phone           varchar(50),
    address         varchar(255),
    photo_url       varchar(500),

    CONSTRAINT uq_personal_infos_resume UNIQUE (resume_id),
    CONSTRAINT fk_personal_infos_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

CREATE TABLE educations (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id           bigint NOT NULL,
    school_type         varchar(50),
    school_name         varchar(100) NOT NULL,
    admission_date      varchar(10),
    graduation_date     varchar(10),
    status              varchar(50),
    is_transfer         boolean NOT NULL DEFAULT false,
    major_name          varchar(100),
    gpa                 numeric(5,2),
    max_gpa             numeric(5,2),
    other_majors        varchar(200),

    CONSTRAINT fk_educations_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_educations_admission_date
        CHECK (admission_date IS NULL OR admission_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_educations_graduation_date
        CHECK (graduation_date IS NULL OR graduation_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_educations_gpa
        CHECK (gpa IS NULL OR gpa >= 0),
    CONSTRAINT chk_educations_max_gpa
        CHECK (max_gpa IS NULL OR max_gpa > 0),
    CONSTRAINT chk_educations_gpa_range
        CHECK (gpa IS NULL OR max_gpa IS NULL OR gpa <= max_gpa)
);

CREATE INDEX ix_educations_resume ON educations (resume_id);

CREATE TABLE experiences (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id           bigint NOT NULL,
    company_name        varchar(100) NOT NULL,
    department_name     varchar(100),
    start_date          varchar(10),
    end_date            varchar(10),
    is_working          boolean NOT NULL DEFAULT false,
    position            varchar(50),
    responsibilities    text,
    salary              varchar(50),
    career_desc         text,

    CONSTRAINT fk_experiences_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_experiences_start_date
        CHECK (start_date IS NULL OR start_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_experiences_end_date
        CHECK (end_date IS NULL OR end_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_experiences_working_end_date
        CHECK (NOT is_working OR end_date IS NULL)
);

CREATE INDEX ix_experiences_resume ON experiences (resume_id);

CREATE TABLE activities (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id       bigint NOT NULL,
    activity_type   varchar(50),
    organization    varchar(100),
    start_date      varchar(10),
    end_date        varchar(10),
    description     text,

    CONSTRAINT fk_activities_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_activities_start_date
        CHECK (start_date IS NULL OR start_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_activities_end_date
        CHECK (end_date IS NULL OR end_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$')
);

CREATE INDEX ix_activities_resume ON activities (resume_id);

CREATE TABLE trainings (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id       bigint NOT NULL,
    name            varchar(150),
    institution     varchar(100),
    start_date      varchar(10),
    end_date        varchar(10),
    description     text,

    CONSTRAINT fk_trainings_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_trainings_start_date
        CHECK (start_date IS NULL OR start_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_trainings_end_date
        CHECK (end_date IS NULL OR end_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$')
);

CREATE INDEX ix_trainings_resume ON trainings (resume_id);

CREATE TABLE certifications (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id           bigint NOT NULL,
    name                varchar(150),
    issuer              varchar(100),
    acquisition_date    varchar(10),

    CONSTRAINT fk_certifications_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_certifications_acquisition_date
        CHECK (acquisition_date IS NULL OR acquisition_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$')
);

CREATE INDEX ix_certifications_resume ON certifications (resume_id);

CREATE TABLE awards (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id       bigint NOT NULL,
    name            varchar(150),
    issuer          varchar(100),
    award_date      varchar(10),
    description     text,

    CONSTRAINT fk_awards_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_awards_award_date
        CHECK (award_date IS NULL OR award_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$')
);

CREATE INDEX ix_awards_resume ON awards (resume_id);

CREATE TABLE overseas_experiences (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id       bigint NOT NULL,
    country_name    varchar(100),
    start_date      varchar(10),
    end_date        varchar(10),
    description     text,

    CONSTRAINT fk_overseas_experiences_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_overseas_experiences_start_date
        CHECK (start_date IS NULL OR start_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_overseas_experiences_end_date
        CHECK (end_date IS NULL OR end_date ~ '^[0-9]{4}\.(0[1-9]|1[0-2])$')
);

CREATE INDEX ix_overseas_experiences_resume
    ON overseas_experiences (resume_id);

CREATE TABLE language_proficiencies (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id           bigint NOT NULL,
    language_name       varchar(50) NOT NULL,
    proficiency_level   varchar(30) NOT NULL,

    CONSTRAINT fk_language_proficiencies_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_language_proficiencies_level
        CHECK (proficiency_level IN ('DAILY', 'BUSINESS', 'NATIVE'))
);

CREATE INDEX ix_language_proficiencies_resume
    ON language_proficiencies (resume_id);

CREATE TABLE resume_chunks (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id       bigint NOT NULL,
    source_type     varchar(30) NOT NULL,
    source_id       bigint NOT NULL,
    chunk_index     integer NOT NULL DEFAULT 0,
    chunk_content   text NOT NULL,
    embedding       vector(1536),
    content_hash    varchar(64),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_resume_chunks_source
        UNIQUE (resume_id, source_type, source_id, chunk_index),
    CONSTRAINT fk_resume_chunks_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
    CONSTRAINT chk_resume_chunks_source_type
        CHECK (source_type IN (
            'EDUCATION', 'EXPERIENCE', 'ACTIVITY', 'TRAINING',
            'CERTIFICATION', 'AWARD', 'OVERSEAS_EXPERIENCE',
            'LANGUAGE', 'COVER_LETTER'
        )),
    CONSTRAINT chk_resume_chunks_index CHECK (chunk_index >= 0),
    CONSTRAINT chk_resume_chunks_content_hash
        CHECK (content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_resume_chunks_resume ON resume_chunks (resume_id);
CREATE INDEX ix_resume_chunks_source_type ON resume_chunks (source_type);
CREATE INDEX ix_resume_chunks_embedding_pending
    ON resume_chunks (resume_id)
    WHERE embedding IS NULL AND chunk_content <> '';

-- =========================================================
-- 3. 사용자 특성과 스킬
-- =========================================================

CREATE TABLE skills (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(100) NOT NULL,
    category        varchar(50),
    description     text,
    embedding       vector(1536),
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_skills_name UNIQUE (name),
    CONSTRAINT chk_skills_category
        CHECK (category IS NULL OR category IN (
            'LANGUAGE', 'FRAMEWORK', 'DATABASE', 'TOOL', 'COMPETENCY'
        ))
);

-- 원본 명세에서 user_evidences가 참조하지만 누락된 사용자 특성 테이블.
CREATE TABLE user_features (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL,
    feature_type            varchar(30) NOT NULL,
    feature_name            varchar(100) NOT NULL,
    feature_value           text,
    extraction_confidence   numeric(4,3),
    is_verified             boolean NOT NULL DEFAULT false,
    verified_at             timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_features_key
        UNIQUE (user_id, feature_type, feature_name),
    CONSTRAINT fk_user_features_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_user_features_type
        CHECK (feature_type IN (
            'STRENGTH', 'WORK_STYLE', 'VALUE', 'INTEREST', 'TRAIT'
        )),
    CONSTRAINT chk_user_features_confidence
        CHECK (extraction_confidence IS NULL OR extraction_confidence BETWEEN 0 AND 1),
    CONSTRAINT chk_user_features_verification
        CHECK (
            (is_verified AND verified_at IS NOT NULL)
            OR (NOT is_verified AND verified_at IS NULL)
        )
);

CREATE INDEX ix_user_features_user ON user_features (user_id);

CREATE TABLE user_skills (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             bigint NOT NULL,
    skill_id            bigint NOT NULL,
    skill_level         smallint NOT NULL DEFAULT 1,
    importance_level    smallint NOT NULL DEFAULT 2,
    mapping_similarity  numeric(4,3),
    is_verified         boolean NOT NULL DEFAULT false,
    verified_at         timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_skills_skill UNIQUE (user_id, skill_id),
    CONSTRAINT fk_user_skills_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_skills_skill
        FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE RESTRICT,
    CONSTRAINT chk_user_skills_level CHECK (skill_level BETWEEN 1 AND 3),
    CONSTRAINT chk_user_skills_importance CHECK (importance_level BETWEEN 1 AND 3),
    CONSTRAINT chk_user_skills_similarity
        CHECK (mapping_similarity IS NULL OR mapping_similarity BETWEEN 0 AND 1),
    CONSTRAINT chk_user_skills_verification
        CHECK (
            (is_verified AND verified_at IS NOT NULL)
            OR (NOT is_verified AND verified_at IS NULL)
        )
);

CREATE INDEX ix_user_skills_user ON user_skills (user_id);
CREATE INDEX ix_user_skills_skill ON user_skills (skill_id);
CREATE INDEX ix_user_skills_importance ON user_skills (importance_level);
CREATE INDEX ix_user_skills_verified ON user_skills (is_verified);

CREATE TABLE user_evidences (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_skill_id           bigint,
    user_feature_id         bigint,
    source_type             varchar(30) NOT NULL,
    source_id               bigint NOT NULL,
    evidence_text           text NOT NULL,
    evidence_summary        text,
    extraction_confidence   numeric(4,3),
    is_primary              boolean NOT NULL DEFAULT false,
    is_important_source     boolean NOT NULL DEFAULT false,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_user_evidences_skill
        FOREIGN KEY (user_skill_id) REFERENCES user_skills(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_evidences_feature
        FOREIGN KEY (user_feature_id) REFERENCES user_features(id) ON DELETE CASCADE,
    CONSTRAINT chk_user_evidences_owner_xor
        CHECK ((user_skill_id IS NOT NULL) <> (user_feature_id IS NOT NULL)),
    CONSTRAINT chk_user_evidences_source_type
        CHECK (source_type IN (
            'EDUCATION', 'EXPERIENCE', 'ACTIVITY', 'TRAINING',
            'CERTIFICATION', 'AWARD', 'OVERSEAS_EXPERIENCE',
            'LANGUAGE', 'COVER_LETTER'
        )),
    CONSTRAINT chk_user_evidences_confidence
        CHECK (extraction_confidence IS NULL OR extraction_confidence BETWEEN 0 AND 1)
);

CREATE INDEX ix_user_evidences_skill ON user_evidences (user_skill_id);
CREATE INDEX ix_user_evidences_feature ON user_evidences (user_feature_id);
CREATE INDEX ix_user_evidences_source ON user_evidences (source_type, source_id);
CREATE INDEX ix_user_evidences_primary ON user_evidences (is_primary);
CREATE UNIQUE INDEX uq_user_evidences_skill_source
    ON user_evidences (user_skill_id, source_type, source_id)
    WHERE user_skill_id IS NOT NULL;
CREATE UNIQUE INDEX uq_user_evidences_feature_source
    ON user_evidences (user_feature_id, source_type, source_id)
    WHERE user_feature_id IS NOT NULL;

-- =========================================================
-- 4. 회사와 채용공고
-- =========================================================

CREATE TABLE industries (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_name   varchar(100) NOT NULL,

    CONSTRAINT uq_industries_name UNIQUE (industry_name)
);

CREATE TABLE job_roles (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_id     bigint NOT NULL,
    job_role_name   varchar(100) NOT NULL,

    CONSTRAINT uq_job_roles_industry_name UNIQUE (industry_id, job_role_name),
    CONSTRAINT fk_job_roles_industry
        FOREIGN KEY (industry_id) REFERENCES industries(id) ON DELETE RESTRICT
);

CREATE INDEX ix_job_roles_industry ON job_roles (industry_id);

CREATE TABLE companies (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    varchar(200) NOT NULL,
    company_size    varchar(50),
    talent_profile  text,
    benefits        text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_companies_name UNIQUE (company_name)
);

CREATE INDEX ix_companies_size ON companies (company_size);

CREATE TABLE job_postings (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               varchar(255) NOT NULL,
    company_id          bigint NOT NULL,
    job_role_id         bigint NOT NULL,
    start_ymd           varchar(8),
    end_ymd             varchar(8),
    headcount           integer,
    career_type         varchar(50),
    hire_type           varchar(255),
    region              varchar(255),
    edu_level           varchar(255),
    position_detail     text,
    main_duty           text,
    qualification       text,
    preference          text,
    disqualify_reason   text,
    process             text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_job_postings_company
        FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_postings_role
        FOREIGN KEY (job_role_id) REFERENCES job_roles(id) ON DELETE RESTRICT,
    CONSTRAINT chk_job_postings_start_ymd
        CHECK (
            start_ymd IS NULL
            OR (
                start_ymd ~ '^[0-9]{8}$'
                AND to_char(to_date(start_ymd, 'YYYYMMDD'), 'YYYYMMDD') = start_ymd
            )
        ),
    CONSTRAINT chk_job_postings_end_ymd
        CHECK (
            end_ymd IS NULL
            OR (
                end_ymd ~ '^[0-9]{8}$'
                AND to_char(to_date(end_ymd, 'YYYYMMDD'), 'YYYYMMDD') = end_ymd
            )
        ),
    CONSTRAINT chk_job_postings_headcount
        CHECK (headcount IS NULL OR headcount >= 0)
);

CREATE INDEX ix_job_postings_company ON job_postings (company_id);
CREATE INDEX ix_job_postings_role ON job_postings (job_role_id);
CREATE INDEX ix_job_postings_end_ymd ON job_postings (end_ymd);
CREATE INDEX ix_job_postings_career_type ON job_postings (career_type);

CREATE TABLE job_posting_chunks (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id      bigint NOT NULL,
    source_type         varchar(50) NOT NULL,
    chunk_index         integer NOT NULL DEFAULT 0,
    chunk_content       text NOT NULL,
    use_for_matching    boolean NOT NULL DEFAULT true,
    embedding           vector(1536),
    content_hash        varchar(64) NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_job_posting_chunks_key
        UNIQUE (job_posting_id, source_type, chunk_index),
    CONSTRAINT fk_job_posting_chunks_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT chk_job_posting_chunks_source_type
        CHECK (source_type IN (
            'POSITION_DETAIL', 'MAIN_TASK', 'REQUIREMENT', 'PREFERENCE',
            'TECH_STACK', 'BENEFIT', 'PROCESS', 'DISQUALIFICATION', 'ETC'
        )),
    CONSTRAINT chk_job_posting_chunks_index CHECK (chunk_index >= 0),
    CONSTRAINT chk_job_posting_chunks_hash
        CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_job_posting_chunks_matching_rule
        CHECK (
            (
                source_type IN ('PROCESS', 'DISQUALIFICATION', 'BENEFIT')
                AND use_for_matching = false
            )
            OR
            (
                source_type NOT IN ('PROCESS', 'DISQUALIFICATION', 'BENEFIT')
                AND use_for_matching = true
            )
        )
);

CREATE INDEX ix_job_posting_chunks_posting
    ON job_posting_chunks (job_posting_id);
CREATE INDEX ix_job_posting_chunks_source
    ON job_posting_chunks (source_type);
CREATE INDEX ix_job_posting_chunks_hash
    ON job_posting_chunks (content_hash);
CREATE INDEX ix_job_posting_chunks_embedding_pending
    ON job_posting_chunks (job_posting_id)
    WHERE embedding IS NULL AND chunk_content <> '' AND use_for_matching = true;

CREATE TABLE job_posting_extraction_meta (
    job_posting_id     bigint PRIMARY KEY,
    input_hash         varchar(64) NOT NULL,
    prompt_version     varchar(32) NOT NULL,
    extraction_model   varchar(64) NOT NULL,
    tech_stacks_json   jsonb NOT NULL DEFAULT '[]'::jsonb,
    benefits_json      jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_job_posting_extraction_meta_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT chk_job_posting_extraction_meta_hash
        CHECK (input_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_job_posting_extraction_meta_tech_array
        CHECK (jsonb_typeof(tech_stacks_json) = 'array'),
    CONSTRAINT chk_job_posting_extraction_meta_benefits_array
        CHECK (jsonb_typeof(benefits_json) = 'array')
);

CREATE INDEX ix_job_posting_extraction_meta_hash
    ON job_posting_extraction_meta (input_hash);

CREATE TABLE job_posting_skills (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id  bigint NOT NULL,
    skill_id        bigint NOT NULL,
    skill_type      varchar(30) NOT NULL,
    skill_level     smallint NOT NULL DEFAULT 1,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_job_posting_skills_skill
        UNIQUE (job_posting_id, skill_id),
    CONSTRAINT fk_job_posting_skills_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_job_posting_skills_skill
        FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE RESTRICT,
    CONSTRAINT chk_job_posting_skills_type
        CHECK (skill_type IN ('REQUIRED', 'PREFERRED', 'RELATED')),
    CONSTRAINT chk_job_posting_skills_level CHECK (skill_level BETWEEN 1 AND 3)
);

CREATE INDEX ix_job_posting_skills_skill ON job_posting_skills (skill_id);
CREATE INDEX ix_job_posting_skills_type ON job_posting_skills (skill_type);

-- =========================================================
-- 5. 챗봇 대화 · 공고 추천
-- =========================================================

CREATE TABLE chat_sessions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL,
    title           varchar(200),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_chat_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX ix_chat_sessions_user_updated
    ON chat_sessions (user_id, updated_at DESC);

CREATE TABLE chat_messages (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          bigint NOT NULL,
    sender_type         varchar(20) NOT NULL,
    content             text NOT NULL,
    extracted_filters   jsonb,
    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE,
    CONSTRAINT chk_chat_messages_sender
        CHECK (sender_type IN ('USER', 'BOT')),
    CONSTRAINT chk_chat_messages_filters_object
        CHECK (extracted_filters IS NULL OR jsonb_typeof(extracted_filters) = 'object')
);

CREATE INDEX ix_chat_messages_session_created
    ON chat_messages (session_id, created_at);

CREATE TABLE recommendations (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL,
    chat_message_id   bigint,
    source            varchar(20) NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_recommendations_chat_message UNIQUE (chat_message_id),
    CONSTRAINT fk_recommendations_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendations_chat_message
        FOREIGN KEY (chat_message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
    CONSTRAINT chk_recommendations_source
        CHECK (source IN ('CHATBOT', 'RESUME_AUTO')),
    CONSTRAINT chk_recommendations_source_message
        CHECK (
            (source = 'CHATBOT' AND chat_message_id IS NOT NULL)
            OR (source = 'RESUME_AUTO' AND chat_message_id IS NULL)
        )
);

CREATE INDEX ix_recommendations_user_created
    ON recommendations (user_id, created_at DESC);

CREATE TABLE recommendation_jobs (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id   bigint NOT NULL,
    job_posting_id      bigint NOT NULL,
    match_score         numeric(5,2),
    reason              text,
    rank_order          integer,

    CONSTRAINT uq_recommendation_jobs_posting
        UNIQUE (recommendation_id, job_posting_id),
    CONSTRAINT fk_recommendation_jobs_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES recommendations(id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendation_jobs_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT chk_recommendation_jobs_score
        CHECK (match_score IS NULL OR match_score BETWEEN 0 AND 100),
    CONSTRAINT chk_recommendation_jobs_rank
        CHECK (rank_order IS NULL OR rank_order > 0)
);

CREATE INDEX ix_recommendation_jobs_posting
    ON recommendation_jobs (job_posting_id);

-- =========================================================
-- 6. 결과 리포트
-- =========================================================

CREATE TABLE analysis_reports (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL,
    job_posting_id  bigint NOT NULL,
    match_score     integer,
    reason          text,
    strengths       text,
    weaknesses      text,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_analysis_reports_user_posting
        UNIQUE (user_id, job_posting_id),
    CONSTRAINT fk_analysis_reports_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_analysis_reports_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT chk_analysis_reports_score
        CHECK (match_score IS NULL OR match_score BETWEEN 0 AND 100)
);

CREATE INDEX ix_analysis_reports_posting
    ON analysis_reports (job_posting_id);

-- =========================================================
-- 7. 학습 로드맵
-- =========================================================

CREATE TABLE roadmaps (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   bigint NOT NULL,
    job_posting_id            bigint NOT NULL,
    report_id                 bigint NOT NULL,
    title                     varchar(255) NOT NULL,
    status                    varchar(50),
    total_estimated_minutes   integer,
    progress_rate             numeric(5,2),
    estimated_end_date        date,
    last_replanned_at         timestamptz,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_roadmaps_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmaps_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmaps_report
        FOREIGN KEY (report_id) REFERENCES analysis_reports(id) ON DELETE CASCADE,
    CONSTRAINT chk_roadmaps_status
        CHECK (status IS NULL OR status IN (
            'DRAFT', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'CANCELLED'
        )),
    CONSTRAINT chk_roadmaps_estimated_minutes
        CHECK (total_estimated_minutes IS NULL OR total_estimated_minutes >= 0),
    CONSTRAINT chk_roadmaps_progress
        CHECK (progress_rate IS NULL OR progress_rate BETWEEN 0 AND 100)
);

CREATE INDEX ix_roadmaps_user ON roadmaps (user_id);
CREATE INDEX ix_roadmaps_posting ON roadmaps (job_posting_id);
CREATE INDEX ix_roadmaps_report ON roadmaps (report_id);

CREATE TABLE roadmap_skills (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id          bigint NOT NULL,
    skill_id            bigint NOT NULL,
    current_level       varchar(20),
    target_level        varchar(20),
    importance          integer,
    priority            integer,
    estimated_minutes   integer,
    progress_rate       numeric(5,2),
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_roadmap_skills_skill UNIQUE (roadmap_id, skill_id),
    CONSTRAINT fk_roadmap_skills_roadmap
        FOREIGN KEY (roadmap_id) REFERENCES roadmaps(id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_skills_skill
        FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE RESTRICT,
    CONSTRAINT chk_roadmap_skills_importance
        CHECK (importance IS NULL OR importance >= 0),
    CONSTRAINT chk_roadmap_skills_priority
        CHECK (priority IS NULL OR priority > 0),
    CONSTRAINT chk_roadmap_skills_estimated_minutes
        CHECK (estimated_minutes IS NULL OR estimated_minutes >= 0),
    CONSTRAINT chk_roadmap_skills_progress
        CHECK (progress_rate IS NULL OR progress_rate BETWEEN 0 AND 100)
);

CREATE INDEX ix_roadmap_skills_skill ON roadmap_skills (skill_id);

CREATE TABLE milestones (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               bigint NOT NULL,
    skill_id              bigint NOT NULL,
    title                 varchar(200) NOT NULL,
    description           text,
    completion_criteria   text,
    difficulty            varchar(50),
    estimated_minutes     integer,
    status                varchar(50),
    progress_rate         numeric(5,2),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_milestones_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestones_skill
        FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE RESTRICT,
    CONSTRAINT chk_milestones_estimated_minutes
        CHECK (estimated_minutes IS NULL OR estimated_minutes >= 0),
    CONSTRAINT chk_milestones_status
        CHECK (status IS NULL OR status IN (
            'NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED'
        )),
    CONSTRAINT chk_milestones_progress
        CHECK (progress_rate IS NULL OR progress_rate BETWEEN 0 AND 100)
);

CREATE INDEX ix_milestones_user ON milestones (user_id);
CREATE INDEX ix_milestones_skill ON milestones (skill_id);

CREATE TABLE roadmap_milestones (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_skill_id    bigint NOT NULL,
    milestone_id        bigint NOT NULL,
    learning_order      integer,
    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_roadmap_milestones_pair
        UNIQUE (roadmap_skill_id, milestone_id),
    CONSTRAINT fk_roadmap_milestones_roadmap_skill
        FOREIGN KEY (roadmap_skill_id) REFERENCES roadmap_skills(id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_milestones_milestone
        FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE CASCADE,
    CONSTRAINT chk_roadmap_milestones_order
        CHECK (learning_order IS NULL OR learning_order > 0)
);

CREATE INDEX ix_roadmap_milestones_milestone
    ON roadmap_milestones (milestone_id);

CREATE TABLE learning_resources (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider          varchar(100),
    external_id       varchar(100),
    resource_type     varchar(50),
    title             varchar(255),
    description       text,
    url               varchar(500),
    thumbnail_url     varchar(500),
    duration_minutes  integer,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_learning_resources_provider_external
        UNIQUE (provider, external_id),
    CONSTRAINT chk_learning_resources_duration
        CHECK (duration_minutes IS NULL OR duration_minutes >= 0)
);

CREATE TABLE resource_recommendations (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id            bigint NOT NULL,
    resource_id             bigint NOT NULL,
    rank_order              integer,
    recommendation_reason   text,
    created_at              timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_resource_recommendations_pair
        UNIQUE (milestone_id, resource_id),
    CONSTRAINT fk_resource_recommendations_milestone
        FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE CASCADE,
    CONSTRAINT fk_resource_recommendations_resource
        FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE CASCADE,
    CONSTRAINT chk_resource_recommendations_rank
        CHECK (rank_order IS NULL OR rank_order > 0)
);

CREATE INDEX ix_resource_recommendations_resource
    ON resource_recommendations (resource_id);

CREATE TABLE learning_progresses (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id        bigint NOT NULL,
    previous_progress   numeric(5,2),
    current_progress    numeric(5,2),
    studied_minutes     integer,
    note                text,
    recorded_at         timestamptz NOT NULL DEFAULT now(),
    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_learning_progresses_milestone
        FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE CASCADE,
    CONSTRAINT chk_learning_progresses_previous
        CHECK (previous_progress IS NULL OR previous_progress BETWEEN 0 AND 100),
    CONSTRAINT chk_learning_progresses_current
        CHECK (current_progress IS NULL OR current_progress BETWEEN 0 AND 100),
    CONSTRAINT chk_learning_progresses_minutes
        CHECK (studied_minutes IS NULL OR studied_minutes >= 0)
);

CREATE INDEX ix_learning_progresses_milestone_recorded
    ON learning_progresses (milestone_id, recorded_at DESC);

-- =========================================================
-- updated_at 자동 갱신 트리거
-- =========================================================

CREATE TRIGGER trg_cover_letter_items_updated_at
    BEFORE UPDATE ON cover_letter_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_resume_chunks_updated_at
    BEFORE UPDATE ON resume_chunks
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_user_features_updated_at
    BEFORE UPDATE ON user_features
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_user_skills_updated_at
    BEFORE UPDATE ON user_skills
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_user_evidences_updated_at
    BEFORE UPDATE ON user_evidences
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_companies_updated_at
    BEFORE UPDATE ON companies
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_job_postings_updated_at
    BEFORE UPDATE ON job_postings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_job_posting_chunks_updated_at
    BEFORE UPDATE ON job_posting_chunks
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_job_posting_extraction_meta_updated_at
    BEFORE UPDATE ON job_posting_extraction_meta
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_chat_sessions_updated_at
    BEFORE UPDATE ON chat_sessions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_roadmaps_updated_at
    BEFORE UPDATE ON roadmaps
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_roadmap_skills_updated_at
    BEFORE UPDATE ON roadmap_skills
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_milestones_updated_at
    BEFORE UPDATE ON milestones
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_learning_resources_updated_at
    BEFORE UPDATE ON learning_resources
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 임베딩용 HNSW 인덱스는 데이터 증가 후 운영 환경에서 별도 생성한다.
-- 예:
-- CREATE INDEX CONCURRENTLY ix_job_posting_chunks_embedding_hnsw
-- ON job_posting_chunks USING hnsw (embedding vector_cosine_ops)
-- WHERE use_for_matching = true AND embedding IS NOT NULL;
