-- companies의 기존 ID를 1 기반에서 0 기반으로 재배치한다.
-- 참조 중인 채용공고가 있는 환경에서도 company_id를 함께 이동한다.

LOCK TABLE job_postings, companies IN ACCESS EXCLUSIVE MODE;

ALTER TABLE job_postings
    DROP CONSTRAINT fk_job_posting_company;

-- GENERATED ALWAYS 상태에서는 명시적 ID 변경이 금지되므로 마이그레이션 동안만 완화한다.
ALTER TABLE companies
    ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 최신 seed는 이미 0 기반일 수 있으므로, 0번 ID가 없을 때만 재배치한다.
-- 기존 ID 범위 밖으로 먼저 이동해 UPDATE 도중의 PK 충돌도 방지한다.
CREATE TEMPORARY TABLE company_reindex_state ON COMMIT DROP AS
SELECT NOT EXISTS (SELECT 1 FROM companies WHERE id = 0) AS required,
       COALESCE(MAX(id) - MIN(id) + 1, 1) AS shift
FROM companies;

UPDATE companies AS company
SET id = company.id + state.shift
FROM company_reindex_state AS state
WHERE state.required;

UPDATE job_postings
SET company_id = company_id - 1
FROM company_reindex_state AS state
WHERE state.required;

UPDATE companies AS company
SET id = company.id - state.shift - 1
FROM company_reindex_state AS state
WHERE state.required;

ALTER TABLE companies
    ALTER COLUMN id SET GENERATED ALWAYS;

ALTER SEQUENCE companies_id_seq
    MINVALUE 0
    START WITH 0;

-- 데이터가 있으면 다음 ID는 MAX(id) + 1, 비어 있으면 첫 ID는 0이 된다.
SELECT setval(
    pg_get_serial_sequence('companies', 'id'),
    COALESCE(MAX(id), 0),
    COUNT(*) > 0
)
FROM companies;

ALTER TABLE job_postings
    ADD CONSTRAINT fk_job_posting_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id)
        ON DELETE RESTRICT;
