spring:
  application:
    name: passed-backend

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/edu}
    username: ${DB_USERNAME:edu}
    password: ${DB_PASSWORD:1234}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true


server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
app:
  dev-current-user-id: ${DEV_CURRENT_USER_ID:257}

external:
  recommendation-ai:
    base-url: ${RECOMMENDATION_AI_BASE_URL:http://localhost:8000}
    connect-timeout-millis: ${RECOMMENDATION_AI_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${RECOMMENDATION_AI_READ_TIMEOUT_MILLIS:300000}
  roadmap-ai:
    base-url: ${ROADMAP_AI_BASE_URL:http://localhost:8000}
    connect-timeout-millis: ${ROADMAP_AI_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${ROADMAP_AI_READ_TIMEOUT_MILLIS:420000}
  cover-letter-ai:
    base-url: ${COVER_LETTER_AI_BASE_URL:http://localhost:8000}
    connect-timeout-millis: ${COVER_LETTER_AI_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${COVER_LETTER_AI_READ_TIMEOUT_MILLIS:180000}

  user-skill-ai:
    base-url: ${USER_SKILL_AI_BASE_URL:http://localhost:8000}
    connect-timeout-millis: ${USER_SKILL_AI_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${USER_SKILL_AI_READ_TIMEOUT_MILLIS:600000}

  learning-competency-ai:
    base-url: ${LEARNING_COMPETENCY_AI_BASE_URL:http://localhost:8000}
    connect-timeout-millis: ${LEARNING_COMPETENCY_AI_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${LEARNING_COMPETENCY_AI_READ_TIMEOUT_MILLIS:600000}


application:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
    cookie:
      secure: ${COOKIE_SECURE:false}
      same-site: ${COOKIE_SAME_SITE:Lax}
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: 1800000
      refresh-token-expiration: 604800000