spring:
  application:
    name: passed-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true


server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details: always

external:
  roadmap-ai:
    base-url: ${ROADMAP_AI_BASE_URL:http://localhost:8000}
    connect-timeout-millis: ${ROADMAP_AI_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${ROADMAP_AI_READ_TIMEOUT_MILLIS:30000}

  cover-letter-ai:
    base-url: ${ROADMAP_AI_BASE_URL:http://localhost:8000}
    connect-timeout-millis: ${ROADMAP_AI_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${ROADMAP_AI_READ_TIMEOUT_MILLIS:420000}