name: Backend CI

on:
  push:
    branches:
      - dev

    paths:
      - "passed-backend/**"
      - ".github/workflows/backend-ci.yml"

  pull_request:
    branches:
      - dev
      - main

    paths:
      - "passed-backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: passed-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew bootJar